[package]
name = "pico-ir-mqtt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bpaf = { version = "0.9.20", features = ["derive"] }
rumqttc = "0.25.0"
serialport = { version = "4.7.3", default-features = false }
